# Dockerfile.dev
FROM node:22-alpine
WORKDIR /usr/src/app

# Dependências úteis p/ builds nativos e Prisma em alpine
RUN apk add --no-cache python3 make g++ bash libc6-compat openssl

# Instala deps (cache pelo package*.json)
COPY package*.json ./
RUN npm ci

# Copia o restante do código
COPY . .

# Nest CLI para start:dev (se precisar)
RUN npm i -g @nestjs/cli

EXPOSE 3000
CMD ["npm", "run", "start:dev"]
