services:
  db:
    image: postgres:16-alpine
    container_name: edu-class-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: edu-class
    ports:
      - '5432:5432'
    volumes:
      - pg-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d edu-class']
      interval: 5s
      timeout: 3s
      retries: 20
    restart: unless-stopped

volumes:
  pg-data:
