# 1) Build
FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

# 2) Runtime
FROM node:20-alpine
WORKDIR /app
ENV NODE_ENV=production
COPY package*.json ./
RUN npm ci --omit=dev
COPY --from=builder /app/dist ./dist
# Se usar Prisma:
COPY prisma ./prisma
RUN npx prisma generate
EXPOSE 3000
# Migrações + start
CMD sh -c "npx prisma migrate deploy && node dist/main.js"

